spring:
  data:
    mongodb:
      database: company
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: true
    database-platform: h2
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  datasource:
    batch:
      driverClassName: org.h2.Driver
      url: jdbc:h2:mem:library;DB_CLOSE_DELAY=-1
    url: jdbc:h2:mem:library;DB_CLOSE_DELAY=-1
    initialization-mode: always
    driverClassName: org.h2.Driver
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
    initialize-schema: always

mongock:
  runner-type: "ApplicationRunner" # default
  #runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.spring.mongock.changelog




